[package]
name = "max6675-station"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spidev = "0.5.1"
rppal = "0.14.1"
anyhow = "1.0.71"
env_logger = "0.10.0"
log = "0.4.17"
